# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\T\AppData\Local\Programs\Python\Python310\TamBN_Python_Mock2\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\T\\AppData\\Local\\Programs\\Python\\Python310\\TamBN_Python_Mock2\\image1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.hcmbutton = QtWidgets.QPushButton(self.centralwidget)
        self.hcmbutton.setGeometry(QtCore.QRect(520, 420, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hcmbutton.setFont(font)
        self.hcmbutton.setObjectName("hcmbutton")
        self.dnbutton = QtWidgets.QPushButton(self.centralwidget)
        self.dnbutton.setGeometry(QtCore.QRect(320, 420, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dnbutton.setFont(font)
        self.dnbutton.setStyleSheet("background: rgb(255, 255, 255);")
        self.dnbutton.setObjectName("dnbutton")
        self.home = QtWidgets.QPushButton(self.centralwidget)
        self.home.setGeometry(QtCore.QRect(300, 40, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.home.setFont(font)
        self.home.setStyleSheet("background: rgb(255,255,255)")
        self.home.setObjectName("home")
        self.logoutbutton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutbutton.setGeometry(QtCore.QRect(530, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.logoutbutton.setFont(font)
        self.logoutbutton.setStyleSheet("background: rgb(255, 255, 255);")
        self.logoutbutton.setObjectName("logoutbutton")
        self.hnbutton = QtWidgets.QPushButton(self.centralwidget)
        self.hnbutton.setGeometry(QtCore.QRect(120, 420, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hnbutton.setFont(font)
        self.hnbutton.setStyleSheet("background: rgb(255,255,255)")
        self.hnbutton.setObjectName("hnbutton")
        self.historybutton = QtWidgets.QPushButton(self.centralwidget)
        self.historybutton.setGeometry(QtCore.QRect(110, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.historybutton.setFont(font)
        self.historybutton.setStyleSheet("background: rgb(255, 255, 255);")
        self.historybutton.setObjectName("historybutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hcmbutton.setText(_translate("MainWindow", "HO CHI MINH"))
        self.dnbutton.setText(_translate("MainWindow", "DA NANG"))
        self.home.setText(_translate("MainWindow", "HOME"))
        self.logoutbutton.setText(_translate("MainWindow", "LOG OUT"))
        self.hnbutton.setText(_translate("MainWindow", "HA NOI"))
        self.historybutton.setText(_translate("MainWindow", "HISTORY"))
import picture_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
